Feature/92 download files
ISPP-G5/NexONG_Backend pull request #102
Opened 2024-03-15 12:55 UTC by FelixoGudiel

This feature aims to fix two major problems in the app.

The first of them is the correct pathing for files. This feature can be checked by clicking in the link in the file field of an object. It should now trigger the download of the file (please upload a file first, as the populate does not contain the files referenced in the mock data (i can add my mock "files" folder so that it works, but i would have to change the gitignore for that)). This can be used for checking the submitted files or for the frontend showing of specific organizational files.

The second of them is the addition of the PATCH method to all api models. PATCH is a very interesting request, because it behaves in a similar way to PUT but with a quirk. A PUT request requires all fields in a `json` to update an object, as it completely overwrites the object. A PATCH, however, will only overwrite the given parameters in the `json`. This way, frontend can update file-related objects without having to upload all the files if they are unchanged. A new option PATCH shoud appear next to the PUT button in the api (given an id, example: meeting/2).

Please, check these functionalities and give me your insights on this theme!

2024-03-15 16:36 UTC, auroranavas commented on nexong/views.py
> +    print(path)
Please, remove this print statement.

2024-03-15 16:53 UTC, auroranavas requested changes
Right now I am trying to make a PATCH to a CenterExit object but I am getting this error:
![image](https://github.com/ISPP-G5/NexONG_Backend/assets/73229219/4e7457ec-1dab-4edb-8088-11acbb1a7e5b)
![image](https://github.com/ISPP-G5/NexONG_Backend/assets/73229219/8046b7df-8de1-44c6-ae7c-4d904caaaa38)

2024-03-15 17:43 UTC, FelixoGudiel commented
Okay, the problem were the validators colliding with incomplete jsons. This has been fixed by checking the validators only if the field to validate is given in the json. Also I have eliminated PATCH permissions for every model that does not have a fileField, as it is problematic for the validators and this functionality is not essential in non fileField-classes. Thank you for your attention!

2024-03-16 10:26 UTC, auroranavas requested changes
Congrats on the PATH fix, it works wonderfully now. There is just a small problem with the files routing. Here's a screenshot. 

![image](https://github.com/ISPP-G5/NexONG_Backend/assets/73229219/07f72be5-175b-4dcb-a9f2-434fddf5cd96)

2024-03-16 11:09 UTC, FelixoGudiel commented
You are right, when the two new classes (punctual donation and homedocument) were created, they took reference in the previous routes, that were not correct. This is the extract with the new classes with the incorrect fields. Now the FileField redirects to `proof_of_payment` and `home_document`.
![image](https://github.com/ISPP-G5/NexONG_Backend/assets/73229175/a21423de-7026-4cd4-8af0-28e7a79bcb26)
Thank you! If you find anything else, tell me ASAP!

2024-03-16 11:12 UTC, auroranavas approved these changes
This is great, you did a really good job. Congrats and thank you for taking into account my feedback!

2024-03-16 11:28 UTC, manortbla approved these changes
Everything looks fine. Congratulations.

2024-03-16 12:06 UTC, pabpercab1 approved these changes
Functionality seems to work well. Well done!

2024-03-16 12:08 UTC, merged