feat: homeDocument new field docType
ISPP-G5/NexONG_Backend pull request #124
Opened 2024-03-24 19:07 UTC by FelixoGudiel

Frontend has communicated that the current homeDocument is not up to date with the requirements. This class is missing an attribute docType that should be a clasifier between documents. The values of this field should be DOCS_INSTITUCIONALES, MEMORIAS_ANUALES,MEMORIAS_ECONOMICAS,BALANCE_CUENTAS,OTROS_DOCS.

2024-03-24 19:33 UTC, auroranavas requested changes

2024-03-24 19:33 UTC, auroranavas commented on populate.json
> +            "title": "documentoDeCasa",
Could you change this title to something more descriptive? Like `balance_cuentas_2023`.

2024-03-24 20:00 UTC, FelixoGudiel commented
Done!

2024-03-24 20:59 UTC, auroranavas reviewed
Now everything's perfect. I want to ask you to add two small changes to our DB. The reason is that when I was checking our deployed app I noticed two strange things that are the backend's fault. 

- The Meeting 'time' field should be `TimeField` and currently it is a DateTimeField.
- Lesson has start_date and end_date de lesson and they should be DateField.

2024-03-26 11:07 UTC, Ahydul approved these changes
It works correctly and the changes are reflected in the db

2024-03-26 11:12 UTC, auroranavas approved these changes
Thank you for going out of your way to make the project better! Good work.

2024-03-26 12:16 UTC, manortbla approved these changes
Thanks for the changes. Good job!

2024-03-27 13:58 UTC, merged