hotfix/129-model change
ISPP-G5/NexONG_Backend pull request #130
Opened 2024-03-26 18:43 UTC by pabpercab1

2024-03-27 10:51 UTC, auroranavas requested changes
I checked all the files' logic and there are a few others that should be changed as well:
- The QuarterMarks marks file should be mandatory.
- The HomeDocument document file should be mandatory.
-_The CenterExitAuthorization authorization file should not be mandatory since it would be posted by the admin without a document so the family can upload the authorization._ (deprecated)

2024-03-30 12:40 UTC, JuanluRM approved these changes
All was changed according to feedback and seems right.

2024-03-30 13:25 UTC, auroranavas approved these changes
Thank you for taking my feedback into account. Good job!

2024-03-31 13:38 UTC, FelixoGudiel approved these changes

2024-03-31 17:06 UTC, merged