Feature/171-fix-email
ISPP-G5/NexONG_Backend pull request #177
Opened 2024-04-13 14:00 UTC by manortbla

In this pr we have made the redirection to the frontend login when you access the activation email link. 
For the translation of the email sent automatically by djoser, I have made changes, such as creating my own template to translate the message but only the last 2 lines of the email have been translated.  I would like to know  if you can think of something about how to do it (I have not found it) or if we leave that part of the issue(#171 ), since the gmail itself comes with a built-in translation tool. 

I await your comments.

2024-04-13 16:44 UTC, auroranavas requested changes
Thank you for your implementation. However, there seems to be a problem. In the PR description you say that only the last two lines of the email are translated, but this is the email I get:

![image](https://github.com/ISPP-G5/NexONG_Backend/assets/73229219/8fe6716b-4c03-4201-ae53-099278be0a62)

You say you made a template, but in the commit called "bug" you removed it. I saw that you can customize the email template in this [tutorial](https://www.youtube.com/watch?v=_IKk553cH2s). From 1:10:00 to 1:19:30. I know it's in hindi 🤣, but I think it's "followable".

Also, about the second point in issue #171. It says `Write in the HTML of the activation the next steps after activating the account (URL to the frontend login using username and password...)`. What it means is that, in the HTML page the mail took you before (the one that said that your account had been activated), you were supposed to write what was the next step for the user to access their new account. For example, it should say something like: `Tu cuenta ha sido activada. Para usarla vaya a (link página frontend) y loguese con su correo y contraseña`. However, I think your approach is actually better 👍.

2024-04-14 07:54 UTC, manortbla commented
Since I didn't get the whole email translated, I decided to delete the changes I made since some of them were made in the settings.py. As well as the template that as I could not use it I also ended up deleting it. I will take a look at the video and apply the feedback for the activation screen. 
Thanks for the feedback @auroranavas

2024-04-17 17:18 UTC, pabpercab1 approved these changes

2024-04-17 18:51 UTC, auroranavas approved these changes
This is good news! I'm glad the tutorial helped this issue. Congrats!

2024-04-17 18:51 UTC, merged