Feature/24 lesson Crud
ISPP-G5/NexONG_Backend pull request #58
Opened 2024-02-28 12:52 UTC by pedlopruz

I have added the serializer along with the view and the route.

2024-03-02 10:35 UTC, manortbla reviewed
I advise you to change the meta class of the LessonSerializer so that if there are any changes in the database model, there won't be any issues in the CRUD operations.

2024-03-03 11:53 UTC, JuanluRM requested changes
There are missing attributes in the Lesson CRUD: start date and end date, most likely due to not having the models updated. And there are no validators on the Attendance Lesson dates, It has to be a current or previous date since it's tracking students assistance to lessons.

2024-03-03 12:48 UTC, JuanluRM commented
Remember as well that the number of selected students in a lesson can't be more than the max capacity of said lesson.

2024-03-03 13:27 UTC, JuanluRM requested changes

2024-03-03 13:27 UTC, JuanluRM commented on nexong/api/Lesson/lessonSerializer.py
> +            validation_error["date"] = "The date must be now or in the past."
This validator triggers a TypeError because it's trying to compare a date attribute with a datetime attribute. Needs to be fixed.

2024-03-03 14:08 UTC, JuanluRM submitted a review, later dismissed
Everything works perfect now. Good job.

2024-03-03 14:15 UTC, manortbla submitted a review, later dismissed
Everything is working fine, good job.

2024-03-03 17:13 UTC, JuanluRM approved these changes

2024-03-03 17:46 UTC, auroranavas approved these changes

2024-03-03 17:50 UTC, pabpercab1 approved these changes
Everything works as expected and the business logic works as expected. Great job!

2024-03-03 17:50 UTC, FelixoGudiel approved these changes

2024-03-03 17:51 UTC, merged