feature/48-user-educator-partner-volunteer-y-family-crud
ISPP-G5/NexONG_Backend pull request #60
Opened 2024-03-01 14:01 UTC by manortbla

We have added the CRUD operations for user, family, partner, volunteer and educator.

2024-03-02 17:57 UTC, pabpercab1 requested changes

2024-03-02 17:57 UTC, pabpercab1 commented on nexong/migrations/0001_initial.py
Merge in your local environment the latest changes of develop, which includes an update in the .env to prevent the migrations from uploading to the repository.

2024-03-02 18:16 UTC, manortbla commented on nexong/migrations/0001_initial.py
Done!

2024-03-02 18:32 UTC, auroranavas requested changes
How can I create a Volunteer, Partner, Educator, Family or EducationCenter? A User can be created but there is no way to create a Volunteer, Partner, Educator, Family or EducationCenter that I know of.

2024-03-02 20:03 UTC, MRomalde commented
For example you can use Postman to make a post request to each endpoint, this is an example of how to make a post request for creating a new educator:
-You select POST in https methods in postman
-Then you make a request in this URL: http://localhost:8000/api/educator
-In the headers column of the request you put content/type in key column and application/json in value column, with this your are able to pass json to the endpoint
-in the Body, you write the information that you will send to the API, in this case:
{
    "birthdate": "2022-04-22"
}
With this you can create a new Educator.

2024-03-02 20:11 UTC, auroranavas approved these changes
Everything works. Good job!

2024-03-02 20:19 UTC, auroranavas approved these changes

2024-03-03 11:24 UTC, JuanluRM approved these changes
No issues where found. Everything works as intended.

2024-03-03 11:24 UTC, pabpercab1 requested changes
You did a great job! But at the moment there are two important issues to solve:

- There is no business logic in these models: For example, I can create an educator with a birthday of 12/12/2030
- There is an issue regarding the methods. I saw that there are two different methods in all your views.py, the GetApiView and the CUDApiView, which divides the methods into two different URLs, one with a slash, and the other one without it. I suggest to follow the same type of structure as the other team members.

2024-03-03 15:07 UTC, JuanluRM approved these changes

2024-03-03 15:52 UTC, JuanluRM submitted a review, later dismissed

2024-03-03 18:29 UTC, JuanluRM submitted a review, later dismissed

2024-03-03 18:39 UTC, auroranavas approved these changes
CRUD operations work. Good work!

2024-03-03 18:41 UTC, JuanluRM submitted a review, later dismissed

2024-03-03 18:47 UTC, auroranavas approved these changes

2024-03-03 18:49 UTC, pabpercab1 approved these changes
Thank you for taking into account my review of your feature. I think that in the end, we are getting a high-quality enhancement. Great teamwork, to both of you.

2024-03-03 18:50 UTC, JuanluRM approved these changes

2024-03-03 18:51 UTC, merged